/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AExpressioncarreExpression6 extends PExpression6
{
    private PExpressioncarre _expressioncarre_;

    public AExpressioncarreExpression6()
    {
        // Constructor
    }

    public AExpressioncarreExpression6(
        @SuppressWarnings("hiding") PExpressioncarre _expressioncarre_)
    {
        // Constructor
        setExpressioncarre(_expressioncarre_);

    }

    @Override
    public Object clone()
    {
        return new AExpressioncarreExpression6(
            cloneNode(this._expressioncarre_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressioncarreExpression6(this);
    }

    public PExpressioncarre getExpressioncarre()
    {
        return this._expressioncarre_;
    }

    public void setExpressioncarre(PExpressioncarre node)
    {
        if(this._expressioncarre_ != null)
        {
            this._expressioncarre_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressioncarre_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressioncarre_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressioncarre_ == child)
        {
            this._expressioncarre_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressioncarre_ == oldChild)
        {
            setExpressioncarre((PExpressioncarre) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
