/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class ADecfonctionListedecfonc extends PListedecfonc
{
    private PFonction _fonction_;
    private PListedecfonc _listedecfonc_;

    public ADecfonctionListedecfonc()
    {
        // Constructor
    }

    public ADecfonctionListedecfonc(
        @SuppressWarnings("hiding") PFonction _fonction_,
        @SuppressWarnings("hiding") PListedecfonc _listedecfonc_)
    {
        // Constructor
        setFonction(_fonction_);

        setListedecfonc(_listedecfonc_);

    }

    @Override
    public Object clone()
    {
        return new ADecfonctionListedecfonc(
            cloneNode(this._fonction_),
            cloneNode(this._listedecfonc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecfonctionListedecfonc(this);
    }

    public PFonction getFonction()
    {
        return this._fonction_;
    }

    public void setFonction(PFonction node)
    {
        if(this._fonction_ != null)
        {
            this._fonction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fonction_ = node;
    }

    public PListedecfonc getListedecfonc()
    {
        return this._listedecfonc_;
    }

    public void setListedecfonc(PListedecfonc node)
    {
        if(this._listedecfonc_ != null)
        {
            this._listedecfonc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listedecfonc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fonction_)
            + toString(this._listedecfonc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fonction_ == child)
        {
            this._fonction_ = null;
            return;
        }

        if(this._listedecfonc_ == child)
        {
            this._listedecfonc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fonction_ == oldChild)
        {
            setFonction((PFonction) newChild);
            return;
        }

        if(this._listedecfonc_ == oldChild)
        {
            setListedecfonc((PListedecfonc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
