/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AExpression6Expression5 extends PExpression5
{
    private PExpression6 _expression6_;

    public AExpression6Expression5()
    {
        // Constructor
    }

    public AExpression6Expression5(
        @SuppressWarnings("hiding") PExpression6 _expression6_)
    {
        // Constructor
        setExpression6(_expression6_);

    }

    @Override
    public Object clone()
    {
        return new AExpression6Expression5(
            cloneNode(this._expression6_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpression6Expression5(this);
    }

    public PExpression6 getExpression6()
    {
        return this._expression6_;
    }

    public void setExpression6(PExpression6 node)
    {
        if(this._expression6_ != null)
        {
            this._expression6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression6_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression6_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression6_ == child)
        {
            this._expression6_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression6_ == oldChild)
        {
            setExpression6((PExpression6) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
