/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AMultExpression5 extends PExpression5
{
    private PExpression5 _expression5_;
    private TMult _mult_;
    private PExpression6 _expression6_;

    public AMultExpression5()
    {
        // Constructor
    }

    public AMultExpression5(
        @SuppressWarnings("hiding") PExpression5 _expression5_,
        @SuppressWarnings("hiding") TMult _mult_,
        @SuppressWarnings("hiding") PExpression6 _expression6_)
    {
        // Constructor
        setExpression5(_expression5_);

        setMult(_mult_);

        setExpression6(_expression6_);

    }

    @Override
    public Object clone()
    {
        return new AMultExpression5(
            cloneNode(this._expression5_),
            cloneNode(this._mult_),
            cloneNode(this._expression6_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultExpression5(this);
    }

    public PExpression5 getExpression5()
    {
        return this._expression5_;
    }

    public void setExpression5(PExpression5 node)
    {
        if(this._expression5_ != null)
        {
            this._expression5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression5_ = node;
    }

    public TMult getMult()
    {
        return this._mult_;
    }

    public void setMult(TMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public PExpression6 getExpression6()
    {
        return this._expression6_;
    }

    public void setExpression6(PExpression6 node)
    {
        if(this._expression6_ != null)
        {
            this._expression6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression6_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression5_)
            + toString(this._mult_)
            + toString(this._expression6_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression5_ == child)
        {
            this._expression5_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._expression6_ == child)
        {
            this._expression6_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression5_ == oldChild)
        {
            setExpression5((PExpression5) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(this._expression6_ == oldChild)
        {
            setExpression6((PExpression6) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
