/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AVraiExpression7 extends PExpression7
{
    private TVrai _vrai_;

    public AVraiExpression7()
    {
        // Constructor
    }

    public AVraiExpression7(
        @SuppressWarnings("hiding") TVrai _vrai_)
    {
        // Constructor
        setVrai(_vrai_);

    }

    @Override
    public Object clone()
    {
        return new AVraiExpression7(
            cloneNode(this._vrai_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVraiExpression7(this);
    }

    public TVrai getVrai()
    {
        return this._vrai_;
    }

    public void setVrai(TVrai node)
    {
        if(this._vrai_ != null)
        {
            this._vrai_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vrai_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vrai_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vrai_ == child)
        {
            this._vrai_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vrai_ == oldChild)
        {
            setVrai((TVrai) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
