<Start>
 <AProgramme>
  <APremierListedecvar>
   <ATableauDecvar>
    <AEntierType>
    </AEntierType>
   </ATableauDecvar>
   <AFinalListedecvarbis>
    <AEpsilon>
    </AEpsilon>
   </AFinalListedecvarbis>
  </APremierListedecvar>
  <ARecursifListedecfonc>
   <ADecfonc>
    <AVideOpttype>
    </AVideOpttype>
    <AVideListedecvar>
     <AEpsilon>
     </AEpsilon>
    </AVideListedecvar>
    <AVideListedecvar>
     <AEpsilon>
     </AEpsilon>
    </AVideListedecvar>
    <AInstrbloc>
     <ARecursifListeinst>
      <AAffectInstr>
       <ATabVar>
        <AExp1Exp>
         <AExp2Exp1>
          <AExp3Exp2>
           <AExp4Exp3>
            <AExp5Exp4>
             <AExp6Exp5>
              <ANombreExp6>
              </ANombreExp6>
             </AExp6Exp5>
            </AExp5Exp4>
           </AExp4Exp3>
          </AExp3Exp2>
         </AExp2Exp1>
        </AExp1Exp>
       </ATabVar>
       <AExp1Exp>
        <AExp2Exp1>
         <AExp3Exp2>
          <AExp4Exp3>
           <AExp5Exp4>
            <AExp6Exp5>
             <ANombreExp6>
             </ANombreExp6>
            </AExp6Exp5>
           </AExp5Exp4>
          </AExp4Exp3>
         </AExp3Exp2>
        </AExp2Exp1>
       </AExp1Exp>
      </AAffectInstr>
      <ARecursifListeinst>
       <AAffectInstr>
        <ATabVar>
         <AExp1Exp>
          <AExp2Exp1>
           <AExp3Exp2>
            <AExp4Exp3>
             <AExp5Exp4>
              <AExp6Exp5>
               <ANombreExp6>
               </ANombreExp6>
              </AExp6Exp5>
             </AExp5Exp4>
            </AExp4Exp3>
           </AExp3Exp2>
          </AExp2Exp1>
         </AExp1Exp>
        </ATabVar>
        <AExp1Exp>
         <AExp2Exp1>
          <AExp3Exp2>
           <AExp4Exp3>
            <AExp5Exp4>
             <AExp6Exp5>
              <ANombreExp6>
              </ANombreExp6>
             </AExp6Exp5>
            </AExp5Exp4>
           </AExp4Exp3>
          </AExp3Exp2>
         </AExp2Exp1>
        </AExp1Exp>
       </AAffectInstr>
       <ARecursifListeinst>
        <AAffectInstr>
         <ATabVar>
          <AExp1Exp>
           <AExp2Exp1>
            <AExp3Exp2>
             <AExp4Exp3>
              <AExp5Exp4>
               <AExp6Exp5>
                <ANombreExp6>
                </ANombreExp6>
               </AExp6Exp5>
              </AExp5Exp4>
             </AExp4Exp3>
            </AExp3Exp2>
           </AExp2Exp1>
          </AExp1Exp>
         </ATabVar>
         <AExp1Exp>
          <AExp2Exp1>
           <AExp3Exp2>
            <AExp4Exp3>
             <AModuloExp4>
              <AExp5Exp4>
               <AExp6Exp5>
                <AVarExp6>
                 <ATabVar>
                  <AExp1Exp>
                   <AExp2Exp1>
                    <AExp3Exp2>
                     <AExp4Exp3>
                      <AExp5Exp4>
                       <AExp6Exp5>
                        <ANombreExp6>
                        </ANombreExp6>
                       </AExp6Exp5>
                      </AExp5Exp4>
                     </AExp4Exp3>
                    </AExp3Exp2>
                   </AExp2Exp1>
                  </AExp1Exp>
                 </ATabVar>
                </AVarExp6>
               </AExp6Exp5>
              </AExp5Exp4>
              <AExp6Exp5>
               <AVarExp6>
                <ATabVar>
                 <AExp1Exp>
                  <AExp2Exp1>
                   <AExp3Exp2>
                    <AExp4Exp3>
                     <AExp5Exp4>
                      <AExp6Exp5>
                       <ANombreExp6>
                       </ANombreExp6>
                      </AExp6Exp5>
                     </AExp5Exp4>
                    </AExp4Exp3>
                   </AExp3Exp2>
                  </AExp2Exp1>
                 </AExp1Exp>
                </ATabVar>
               </AVarExp6>
              </AExp6Exp5>
             </AModuloExp4>
            </AExp4Exp3>
           </AExp3Exp2>
          </AExp2Exp1>
         </AExp1Exp>
        </AAffectInstr>
        <ARecursifListeinst>
         <AEcritureInstr>
          <AExp1Exp>
           <AExp2Exp1>
            <AExp3Exp2>
             <AExp4Exp3>
              <AExp5Exp4>
               <AExp6Exp5>
                <AVarExp6>
                 <ATabVar>
                  <AExp1Exp>
                   <AExp2Exp1>
                    <AExp3Exp2>
                     <AExp4Exp3>
                      <AExp5Exp4>
                       <AExp6Exp5>
                        <ANombreExp6>
                        </ANombreExp6>
                       </AExp6Exp5>
                      </AExp5Exp4>
                     </AExp4Exp3>
                    </AExp3Exp2>
                   </AExp2Exp1>
                  </AExp1Exp>
                 </ATabVar>
                </AVarExp6>
               </AExp6Exp5>
              </AExp5Exp4>
             </AExp4Exp3>
            </AExp3Exp2>
           </AExp2Exp1>
          </AExp1Exp>
         </AEcritureInstr>
         <AFinalListeinst>
          <AEpsilon>
          </AEpsilon>
         </AFinalListeinst>
        </ARecursifListeinst>
       </ARecursifListeinst>
      </ARecursifListeinst>
     </ARecursifListeinst>
    </AInstrbloc>
   </ADecfonc>
   <AFinalListedecfonc>
    <AEpsilon>
    </AEpsilon>
   </AFinalListedecfonc>
  </ARecursifListedecfonc>
 </AProgramme>
</Start>
