<Start>
 <AProgramme>
  <APremierListedecvar>
   <AScalaireDecvar>
    <AEntierType>
    </AEntierType>
   </AScalaireDecvar>
   <ARecursifListedecvarbis>
    <AScalaireDecvar>
     <AEntierType>
     </AEntierType>
    </AScalaireDecvar>
    <AFinalListedecvarbis>
     <AEpsilon>
     </AEpsilon>
    </AFinalListedecvarbis>
   </ARecursifListedecvarbis>
  </APremierListedecvar>
  <ARecursifListedecfonc>
   <ADecfonc>
    <AVideOpttype>
    </AVideOpttype>
    <AVideListedecvar>
     <AEpsilon>
     </AEpsilon>
    </AVideListedecvar>
    <AVideListedecvar>
     <AEpsilon>
     </AEpsilon>
    </AVideListedecvar>
    <AInstrbloc>
     <ARecursifListeinst>
      <AAffectInstr>
       <ASimpleVar>
       </ASimpleVar>
       <AExp1Exp>
        <AExp2Exp1>
         <AExp3Exp2>
          <AExp4Exp3>
           <AExp5Exp4>
            <AExp6Exp5>
             <ANombreExp6>
             </ANombreExp6>
            </AExp6Exp5>
           </AExp5Exp4>
          </AExp4Exp3>
         </AExp3Exp2>
        </AExp2Exp1>
       </AExp1Exp>
      </AAffectInstr>
      <ARecursifListeinst>
       <AAffectInstr>
        <ASimpleVar>
        </ASimpleVar>
        <AExp1Exp>
         <AExp2Exp1>
          <AExp3Exp2>
           <AExp4Exp3>
            <AExp5Exp4>
             <AExp6Exp5>
              <ANombreExp6>
              </ANombreExp6>
             </AExp6Exp5>
            </AExp5Exp4>
           </AExp4Exp3>
          </AExp3Exp2>
         </AExp2Exp1>
        </AExp1Exp>
       </AAffectInstr>
       <ARecursifListeinst>
        <AEcritureInstr>
         <AExp1Exp>
          <AExp2Exp1>
           <AExp3Exp2>
            <AExp4Exp3>
             <AModuloExp4>
              <AExp5Exp4>
               <AExp6Exp5>
                <AVarExp6>
                 <ASimpleVar>
                 </ASimpleVar>
                </AVarExp6>
               </AExp6Exp5>
              </AExp5Exp4>
              <AExp6Exp5>
               <AVarExp6>
                <ASimpleVar>
                </ASimpleVar>
               </AVarExp6>
              </AExp6Exp5>
             </AModuloExp4>
            </AExp4Exp3>
           </AExp3Exp2>
          </AExp2Exp1>
         </AExp1Exp>
        </AEcritureInstr>
        <AFinalListeinst>
         <AEpsilon>
         </AEpsilon>
        </AFinalListeinst>
       </ARecursifListeinst>
      </ARecursifListeinst>
     </ARecursifListeinst>
    </AInstrbloc>
   </ADecfonc>
   <AFinalListedecfonc>
    <AEpsilon>
    </AEpsilon>
   </AFinalListedecfonc>
  </ARecursifListedecfonc>
 </AProgramme>
</Start>
