/* This file was generated by SableCC (http://www.sablecc.org/). */

package l.node;

import l.analysis.*;

@SuppressWarnings("nls")
public final class TCarre extends Token
{
    public TCarre()
    {
        super.setText("**");
    }

    public TCarre(int line, int pos)
    {
        super.setText("**");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCarre(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCarre(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCarre text.");
    }
}
